load("@buck2-haskell//:defs.bzl", "haskell_binary", "haskell_toolchain_library")
load("@toolchains//:libs.bzl", "toolchain_libraries")

python_bootstrap_binary(
    name = "generate_toolchain_libs",
    main = "generate_toolchain_libs.py",
)

[haskell_toolchain_library(name = lib, visibility = ["//..."]) for lib in toolchain_libraries]
